TrajectoryPlannerROS:
   max_vel_x: 0.5
   min_vel_x: 0.1

   
   max_vel_theta: 0.15
   min_vel_theta: -0.15

   max_rotational_vel: 0.15
   min_in_place_rotational_vel: 0.01
   min_in_place_vel_theta: 0.01

   acc_lim_x: 1.5
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 1.2

   holonomic_robot: false

