obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.2475, 0.3125], [0.2475, -0.3125], [-0.2475, -0.3125], [-0.2475, 0.3125]]
footprint_inflation: 0.01
inflation_radius: 0.15
observation_sources: point_cloud_sensor

# 全局和局部规划都使用点云话题 /cloud_topic
point_cloud_sensor: {
  sensor_frame: base_link,
  data_type: PointCloud2,
  observation_persistence: 0.0,  
  topic: /dlonng_no_ground_cloud,
  max_obstacle_height: 0.6,
  min_obstacle_height: 0.0,
  marking: true, 
  clearing: true, 
}
