# 先测试 base_local_planner
TebLocalPlannerROS:
  odom_topic: odom
  map_frame: map

  # Robot Configuration Parameters
  max_vel_x: 0.30
  max_vel_x_backwards: 0.00
  max_vel_y: 0.0
  max_vel_theta: 1.0
  acc_lim_x: 0.5
  acc_lim_theta: 1.0
  footprint_model:
    type: "point"

  # Obstacles
  min_obstacle_dist:  0.36
  inflation_dist: 0.38 
  dynamic_obstacle_inflation_dist: 0.40

  # Optimization
  no_inner_iterations: 2
  holonomic_robot: false
  

