obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.175, 0.175], [0.175, -0.175], [-0.175, -0.175], [-0.175, 0.175]]
footprint_inflation: 0.01
robot_radius: 0.175
inflation_radius: 0.15
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
# 全局和局部规划都使用点云话题 /cloud_topic
scan: {data_type: PointCloud2, topic: /rslidar_points, marking: true, clearing: true, expected_update_rate: 0}
