<?xml version="1.0"?>

<robot name="agilex_mini"
    xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name="length_wheel" value="0.045" />
    <xacro:property name="radius_wheel" value="0.070" />

    <xacro:property name="length_body" value="0.495" />
    <xacro:property name="width_body" value="0.625" />
    <xacro:property name="height_body" value="0.140" />

    <xacro:property name="rslidar_length" value="0.0817" />
    <xacro:property name="rslidar_radius" value="0.0535" />

    <xacro:property name="length_sensor_support" value="${2 * rslidar_radius}" />
    <xacro:property name="width_sensor_support" value="0.23" />
    <xacro:property name="height_sensor_support" value="0.23" />

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <link name="base_footprint">
        <visual>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
        <xacro:default_inertial mass="0.0001"/>
    </link>

    <gazebo reference="base_footprint">
        <material>Gazebo/Green</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <xacro:include filename="$(find agilex_description)/urdf/xacro/gazebo/agilex_mini_gazebo.gazebo" />

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${length_body} ${width_body} ${height_body}"/>
            </geometry>

            <origin rpy="0 0 1.5707" xyz="0 0 ${0.5 * height_body}"/>

            <material name="white">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <box size="${length_body} ${width_body} ${height_body}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="10"/>
    </link>

    <link name="wheel_1">
        <visual>
            <geometry>
                <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
            </geometry>
            <!-- <origin rpy="0 1.5 0" xyz="0.1 0.1 0"/> -->
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="1"/>
    </link>

    <link name="wheel_2">
        <visual>
            <geometry>
                <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
            </geometry>
            <!-- <origin rpy="0 1.5 0" xyz="-0.1 0.1 0"/> -->
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="1"/>

    </link>

    <link name="wheel_3">
        <visual>
            <geometry>
                <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
            </geometry>
            <!-- <origin rpy="0 1.5 0" xyz="0.1 -0.1 0"/> -->

            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="1"/>
    </link>

    <link name="wheel_4">
        <visual>
            <geometry>
                <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
            </geometry>
            <!--    <origin rpy="0 1.5 0" xyz="-0.1 -0.1 0"/> -->
            <origin rpy="0 0 0" xyz="0 0 0" />
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="1"/>
    </link>

    <joint name="base_to_wheel1" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_1"/>
        <origin rpy="-1.5707 0 0" xyz="${0.5 * width_body - radius_wheel} ${0.5 * length_body + 0.8 * length_wheel} 0"/>
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_to_wheel2" type="continuous">
        <axis xyz="0 0 1" />
        <anchor xyz="0 0 0" />
        <limit effort="100" velocity="100" />
        <parent link="base_link"/>
        <child link="wheel_2"/>
        <origin rpy="-1.5707 0 0" xyz="-${0.5 * width_body - radius_wheel} ${0.5 * length_body + 0.8 * length_wheel} 0"/>
    </joint>

    <joint name="base_to_wheel3" type="continuous">
        <parent link="base_link"/>
        <axis xyz="0 0 1" />
        <child link="wheel_3"/>
        <origin rpy="-1.5707 0 0" xyz="${0.5 * width_body - radius_wheel} -${0.5 * length_body + 0.8 * length_wheel} 0"/>
    </joint>

    <joint name="base_to_wheel4" type="continuous">
        <parent link="base_link"/>
        <axis xyz="0 0 1" />
        <child link="wheel_4"/>
        <origin rpy="-1.5707 0 0" xyz="-${0.5 * width_body - radius_wheel} -${0.5 * length_body + 0.8 * length_wheel} 0"/>
    </joint>

    <link name="sensor_support">
        <visual>
            <geometry>
                <box size="${length_sensor_support} ${width_sensor_support} ${height_sensor_support}"/>
            </geometry>
            <material name="white">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
    </link>

    <joint name="sensor_support_joint" type="fixed">
        <parent link="base_link"/>
        <child link="sensor_support"/>
        <origin rpy="0 0 0" xyz="${0.5 * width_body - 0.5 * length_sensor_support} 0 ${height_body + 0.5 * height_sensor_support}"/>
    </joint>

    <link name="zed_camera">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <!-- <box size="0.033 0.175 0.030"/> -->
                <mesh filename="package://agilex_description/meshes/zed2.stl" />
            </geometry>

            <!-- https://github.com/stereolabs/zed-ros-wrapper/blob/master/zed_wrapper/urdf/include/materials.urdf.xacro -->
            <material name="zed2_mat">
                <color rgba="0.25 0.25 0.25 0.99"/>
            </material>
        </visual>

        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.033 0.175 0.030"/>
            </geometry>
        </collision>
    </link>

    <joint name="zed_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="${0.5 * length_sensor_support} 0 ${0.5 * height_sensor_support - 0.5 * 0.030}" rpy="0 0 0"/>
        <parent link="sensor_support"/>
        <child link="zed_camera"/>
    </joint>

    <link name="rslidar">
        <visual>
            <geometry>
                <!-- <cylinder length = "0.03" radius = "0.03"/> -->
                <mesh filename="package://agilex_description/meshes/robosense_16.dae" />
            </geometry>

            <origin rpy="-1.5707 0 0" xyz="0 0 0"/>

            <material name="white">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <!-- <cylinder length = "0.03" radius = "0.03"/> -->
                <cylinder radius="${rslidar_radius}" length="${rslidar_length}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>

    <joint name="rslidar_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0 0 ${0.5 * height_sensor_support}" rpy="0 0 0"/>
        <parent link="sensor_support"/>
        <child link="rslidar"/>
    </joint>

</robot>