<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find agilex_description)/urdf/xacro/gazebo/agilex_scout_base_gazebo.xacro" />
    
    <xacro:include filename="$(find agilex_description)/urdf/xacro/sensors/agilex_scout_rslidar_gazebo.xacro" />

    <xacro:property name="lidar_hight" value="0.08" />
    <xacro:property name="platform_hight" value="0.3" />

    <xacro:property name="lidar_offset_x" value="0.209" />
    <xacro:property name="lidar_offset_y" value="0" />
    <xacro:property name="lidar_offset_z" value="${lidar_hight/2 + platform_hight + base_box_z + base_z/2}" />

    
    <joint name="lidar_joint" type="fixed">
        <origin xyz="${lidar_offset_x} ${lidar_offset_y} ${lidar_offset_z}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="laser_link"/>
    </joint>

    <xacro:rplidar prefix="laser"/> 
    <xacro:include filename="$(find agilex_description)/urdf/xacro/sensors/agilex_scout_kinect_gazebo.xacro" />

    <xacro:property name="kinect_offset_x" value="0.239" />
    <xacro:property name="kinect_offset_y" value="0" />
    <xacro:property name="kinect_offset_z" value="${platform_hight + base_box_z + base_z/2 - 0.034}" />

    <!-- kinect -->
    <joint name="kinect_joint" type="fixed">
        <origin xyz="${kinect_offset_x} ${kinect_offset_y} ${kinect_offset_z}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="kinect_link"/>
    </joint>

    <xacro:kinect_camera prefix="kinect"/>

    <xacro:property name="imu_length_x" value="0.06" />
    <xacro:property name="imu_length_y" value="0.04" />
    <xacro:property name="imu_length_z" value="0.022" />
    <!-- before imu_offset_x = 0.209 -->
    <xacro:property name="imu_offset_x" value="0" />
    <xacro:property name="imu_offset_y" value="0" />
    <xacro:property name="imu_offset_z" value="${imu_length_z/2  + base_box_z + base_z/2}" />

    
   
    <link name="imu_link">
        <visual>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                 <box size="${imu_length_x} ${imu_length_y} ${imu_length_z}" />
            </geometry>
            <material name="yellow" />
        </visual>
        <collision>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${imu_length_x} ${imu_length_y} ${imu_length_z}" />
            </geometry>
        </collision>   
        <xacro:default_inertial mass="10"/>
    </link>
    
    <joint name="imu_joint" type="fixed">
        <origin xyz="${imu_offset_x} ${imu_offset_y} ${imu_offset_z}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>

    <xacro:property name="gps_radius" value="0.076" />
    <xacro:property name="gps_length" value="0.05" />
    <xacro:property name="gps_offset_x" value="${base_x/2}" />
    <xacro:property name="gps_offset_y" value="0" />
    <xacro:property name="gps_offset_z" value="${gps_length/2  + base_box_z + base_z/2}" />

    <link name="gps_link_front">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${gps_radius}" length = "${gps_length}"/>
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${gps_radius}" length = "${gps_length}"/>
            </geometry>
        </collision>   
        <xacro:default_inertial mass="10"/>
    </link>
    <joint name="gps_front_joint" type="fixed">
        <origin xyz="${gps_offset_x} ${gps_offset_y} ${gps_offset_z}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="gps_link_front"/>
    </joint>

    <link name="gps_link_back">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${gps_radius}" length = "${gps_length}"/>
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${gps_radius}" length = "${gps_length}"/>
            </geometry>
        </collision>   
        <xacro:default_inertial mass="10"/>
    </link>
    <joint name="gps_back_joint" type="fixed">
        <origin xyz="${-gps_offset_x} ${gps_offset_y} ${gps_offset_z}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="gps_link_back"/>
    </joint>

    <mbot_base_gazebo/>

</robot>
